### PR TITLE
Change custom login page example to use `window.TL`

### PR DESCRIPTION
**Pull request by pvanheus**
This  brings the example in line with the change introduced in https://github.com/phac-nml/irida/commit/5da6359ba0fbfc818eb023423fe3416a0947e2fe

## Description of changes
What did you change in this pull request?  Provide a description of files changed, user interactions changed, etc.  Include how to test your changes.

## Related issue
Link to the GitHub issue this pull request addresses using the `#issuenum` format.  If it completes an issue, use `Fixes #issuenum` to automatically close the issue.

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

* [x] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.
* [x] Tests added (or description of how to test) for any new features.
* [x] User documentation updated for UI or technical changes.

### CODE REVIEW

**Comment by pvanheus** [comment]
Not sure if a change to CHANGELOG.md is necessary for this?

**Comment by joshsadam** [comment]
@pvanheus Thanks for updating this, something that I totally over looked.  Can you fix the conflict in the CHANGELOG.  It looks like a random failing tests (hate those), I restarted them.  Thanks 😊

**Review by joshsadam — CHANGES_REQUESTED** [review]
~~This is really appreciated, please just update the CHANGELOG and I will accept it.~~ Sorry, I don't know why I added this, this is great, thank you.  I updated a merge conflict and will merge this in.  Thank you for updating this.

**Review by joshsadam — APPROVED** [review]
Thanks for doing this, sorry it took so long to get to.

**Pull request merged**
