### PR TITLE
Remove Clojure repl

### PR DESCRIPTION
**Pull request by tom114**
## Description of changes
Removed the Clojure REPL from the `dev` profile and from the project as it was unused.

## Related issue
N/A

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

* [x] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.
~* [ ] Tests added (or description of how to test) for any new features.~
* [x] User documentation updated for UI or technical changes.

### CODE REVIEW

**Comment by apetkau** [comment]
Looks good. I will merge when tests pass.

**Comment by dfornika** [comment]
:cry:

**Comment by apetkau** [comment]
@dfornika were you using this? We weren't aware of anyone who was making use of this feature.

**Comment by tom114** [comment]
Closing as people are using this feature.

**Comment by dfornika** [comment]
I'm not actively using it but had hoped to use it a bit in future. I don't have any really concrete plans though, so I'm happy to defer to the core development team on whether this stays or goes. I could keep it in my own fork if it's removed here.

**Comment by tom114** [comment]
Closed PR since this is a wanted feature.  We may re-investigate in the future.

**Pull request closed without merging**
