### PR TITLE
Sample details refactor/ cleanup

### PR DESCRIPTION
**Pull request by deepsidhu85**
## Description of changes
What did you change in this pull request?  Provide a description of files changed, user interactions changed, etc.  Include how to test your changes.

Removed files and translations that are no longer required. 

## Related issue
Link to the GitHub issue this pull request addresses using the `#issuenum` format.  If it completes an issue, use `Fixes #issuenum` to automatically close the issue.

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

~* [ ] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.~
~* [ ] Tests added (or description of how to test) for any new features.~
~* [ ] User documentation updated for UI or technical changes.~

### CODE REVIEW

**Review by ericenns — APPROVED** [review]
👍 This looks good to me

**Comment by joshsadam** [comment]
I think you still need to remove `src/main/webapp/resources/css/pages/sample-files.css`

**Review by joshsadam — CHANGES_REQUESTED** [review]
I think those last 2 files and this should be GTG.  Thanks @deepsidhu85 and @ericenns

**Review by joshsadam — APPROVED** [review]
Looks good to me, thanks @deepsidhu85

**Pull request merged**
