### PR TITLE
Fix parameter null values

### LINKED ISSUE #1052: Biohansel Null Pointer Exception when using defaults
## Describe the bug
The pipeline input allows you to submit without selecting a required input:
image

From singleton log while submitting to galaxy
```
21 Jul 2021 04:50:30,272 DEBUG ca.corefacility.bioinformatics.irida.service.analysis.workspace.galaxy.AnalysisParameterServiceGalaxy:78 - Parameter with name=bio_hansel-1-type_of_scheme.scheme_type, for workflow=IridaWorkflow [workflowDescription=IridaWorkflowDescription [id=0e8738e6-2aeb-4627-9d6e-15ae32f21c44, name=bio_hansel, version=2.0.0, analysisType=BIO_HANSEL], workflowStructure=IridaWorkflowStructure [workflowFile=/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/ca/corefacility/bioinformatics/irida/model/workflow/analysis/type/workflows/BioHansel/2.0.0/irida_workflow_structure.ga]], has no value set, using defaultValue=null
21 Jul 2021 04:50:30,273 ERROR ca.corefacility.bioinformatics.irida.service.analysis.execution.AnalysisExecutionServiceAspect:65 - Error occured for submission: AnalysisSubmission [id=174, name=bio_hansel__7-20-2021_SRR3028776, submitter=nolan.woods, workflowId=0e8738e6-2aeb-4627-9d6e-15ae32f21c44, analysisState=SUBMITTING, analysisCleanedState=NOT_CLEANED] changing to state ERROR
java.lang.NullPointerException: value is null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:897)
	at ca.corefacility.bioinformatics.irida.service.analysis.workspace.galaxy.ParameterBuilderGalaxy.addParameter(ParameterBuilderGalaxy.java:106)
	at ca.corefacility.bioinformatics.irida.service.analysis.workspace.galaxy.AnalysisParameterServiceGalaxy.prepareAnalysisParameters(AnalysisParameterServiceGalaxy.java:86)
	at ca.corefacility.bioinformatics.irida.service.analysis.workspace.galaxy.AnalysisWorkspaceServiceGalaxy.prepareAnalysisFiles(AnalysisWorkspaceServiceGalaxy.java:213)
	at ca.corefacility.bioinformatics.irida.service.analysis.execution.galaxy.AnalysisExecutionServiceGalaxyAsync.executeAnalysis(AnalysisExecutionServiceGalaxyAsync.java:147)
	at ca.corefacility.bioinformatics.irida.service.analysis.execution.galaxy.AnalysisExecutionServiceGalaxyAsync$$FastClassBySpringCGLIB$$fc2d896.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at ca.corefacility.bioinformatics.irida.service.analysis.annotations.RunAsUserAspect.setSecurityContextFromAnalysisSubmission(RunAsUserAspect.java:100)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:62)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at org.springframework.security.concurrent.DelegatingSecurityContextCallable.call(DelegatingSecurityContextCallable.java:87)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

## Steps to reproduce the problem
What were you doing when you encountered the problem?
1. Input SRR3028776
2. Do not select a subtype (both radio boxes empty)
2. Run biohansel pipline

## Expected behaviour
What did you expect to happen?
Complete successfully

## Additional context
Additional information to help solve the problem.  Test files, screenshots, IRIDA version information can go here.
IRIDA 21.05.2
#316

### PR DESCRIPTION
**Pull request by deepsidhu85**
## Description of changes
What did you change in this pull request?  Provide a description of files changed, user interactions changed, etc.  Include how to test your changes.

Updated `InputWithOptions` component with validation rules for if a parameter is required and set initial values if the parameter has them set.

**If parameter is required but the initial value is not set or if a user doesn't select one of the required options:**

BiohanselSubtypingFix

**If initial value is set for a parameter then it will be selected by default (Can be changed by the user)**

BiohanselSubtypingFixIV

## Related issue
Link to the GitHub issue this pull request addresses using the `#issuenum` format.  If it completes an issue, use `Fixes #issuenum` to automatically close the issue.

Fixes #1052 

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

* [X] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.
* [X] Tests added (or description of how to test) for any new features.
~* [ ] User documentation updated for UI or technical changes.~

### CODE REVIEW

**Review by joshsadam — CHANGES_REQUESTED** [review]
This looks good.  Can you add some testing for it please.

**Comment by deepsidhu85** [comment]
> This looks good. Can you add some testing for it please.

Thanks! Yup working on it as we speak :)

**Review by ericenns — APPROVED** [review]
👍 Thanks for fixing this Deep it looks great

**Review by joshsadam — APPROVED** [review]
Looks good to me.

**Pull request merged**
