### PR TITLE
Cart Galaxy Redirect and Galaxy in page status

### PR DESCRIPTION
**Pull request by joshsadam**
## Description of changes
galaxy-alert

 - Display an alert at the top of the page if the user in a Galaxy session
 - User can remove the Galaxy session
 - If they are in the cart and remove the galaxy session, redirect them to the pipelines page.

## Related issue
Related to #192

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

~~* [ ] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.~~
~~* [ ] Tests added (or description of how to test) for any new features.~~
~~* [ ] User documentation updated for UI or technical changes.~~

### CODE REVIEW

**Comment by apetkau** [comment]
Thanks @josh. Looks amazing.

However, I can't seem to access any menus any more if I directly log into IRIDA. For example, if I click **Projects** nothing get's displayed:

image

I suspect the menus are opening up behind the main screen and so are hidden?

**Comment by joshsadam** [comment]
Thanks @apetkau , you're right!  fixed in 244dd91a55c90f8b504d81e479b00c43c319bb72

**Comment by joshsadam** [comment]
Thanks @apetkau it was a css thing, Fixed in 930683226e6763d796c82836c0bd9306d9302c55

**Comment by joshsadam** [comment]
I think every you asked for (except the library name) should be updated in that last commit.  Thanks for the input @apetkau. 

@Takadonet Can you write here exactly why we don't need to have the library name input, I am passing a string that is `IRIDA-<timestamp>` as the library name.

**Comment by Takadonet** [comment]
Galaxy has limitation where we cannot directly upload files into an user history so we have to first upload into a data library.  My hope that users would just share data library with others  instead of re-downloading reads again from IRIDA but it is not the case. 

Having the data library exposed in the window just added extra complexities for no benefit to the user.

**Comment by apetkau** [comment]
Thanks @Takadonet and @joshsadam that makes sense. I didn't realize we were switching over to just auto-naming data libraries as `IRIDA-<timestamp>`.

**Comment by apetkau** [comment]
This looks great to me @joshsadam. I'm merging it in.

**Pull request merged**
