### PR TITLE
Make carousel controls transparent on login page

### PR DESCRIPTION
**Pull request by dfornika**
Minor aesthetic change, makes the sides of the logo banner carousel on the login page transparent instead of a grey gradient. Also hides the white dots that overlap some logos.

### CODE REVIEW

**Comment by dfornika** [comment]
Before:
screen shot 2018-03-16 at 4 27 09 pm
After:
screen shot 2018-03-16 at 5 17 47 pm

**Comment by dfornika** [comment]
It seems to me that the failing test is unrelated to the changes in this pull request. It's something to do with a corrupted database state during a concurrent REST API test.

**Comment by apetkau** [comment]
Thanks.  Yes, the REST API tests sometimes fail to run, and I'm not sure why since if you push the code once more they will succeed again.

**Comment by dfornika** [comment]
It looks like the failed test was `ProjectSamplesIT.testAddMultithreadedSamplesToProject`:

```
Results :

Tests in error: 
ca.corefacility.bioinformatics.irida.web.controller.test.integration.project.ProjectSamplesIT.testAddMultithreadedSamplesToProject(ca.corefacility.bioinformatics.irida.web.controller.test.integration.project.ProjectSamplesIT)
  Run 1: ProjectSamplesIT.testAddMultithreadedSamplesToProject:142 All responses should be created.
  Run 2: ProjectSamplesIT.testAddMultithreadedSamplesToProject:142 All responses should be created.
  Run 3: ProjectSamplesIT.testAddMultithreadedSamplesToProject:142 All responses should be created.
  Run 4: ProjectSamplesIT.testAddMultithreadedSamplesToProject:142 All responses should be created.
  Run 5: ProjectSamplesIT.testAddMultithreadedSamplesToProject:142 All responses should be created.
  Run 6: ProjectSamplesIT.testAddMultithreadedSamplesToProject:142 All responses should be created.
  Run 7: ProjectSamplesIT.testAddMultithreadedSamplesToProject » MySQLIntegrityConstraintViolation

Flaked tests: 
ca.corefacility.bioinformatics.irida.web.controller.test.integration.project.ProjectUsersIT.testRemoveUserFromProject(ca.corefacility.bioinformatics.irida.web.controller.test.integration.project.ProjectUsersIT)
  Run 1: ProjectUsersIT.testRemoveUserFromProject » MySQLIntegrityConstraintViolation C...
  Run 2: PASS


Tests run: 66, Failures: 0, Errors: 1, Skipped: 0, Flakes: 1
```

...so if it involves multi-threaded database mutation then it would make sense that there is some non-deterministic behaviour hiding in there somewhere.

**Comment by apetkau** [comment]
Thanks @dfornika this looks great.

**Pull request merged**
